services:
- type: pserv
  name: n8n-db
  plan: free
  databaseName: n8n
  databaseUser: n8n_user
  region: oregon

- type: web
  name: n8n
  plan: free
  region: oregon
  image:
    url: n8nio/n8n:latest
  healthCheckPath: /healthz
  envVars:
  - key: DB_TYPE
    value: postgresdb
  - key: DB_POSTGRESDB_DATABASE
    fromService:
      type: pserv
      name: n8n-db
      property: databaseName
  - key: DB_POSTGRESDB_HOST
    fromService:
      type: pserv
      name: n8n-db
      property: host
  - key: DB_POSTGRESDB_PORT
    fromService:
      type: pserv
      name: n8n-db
      property: port
  - key: DB_POSTGRESDB_USER
    fromService:
      type: pserv
      name: n8n-db
      property: databaseUser
  - key: DB_POSTGRESDB_PASSWORD
    fromService:
      type: pserv
      name: n8n-db
      property: password
  - key: WEBHOOK_URL
    fromService:
      type: web
      name: n8n
      property: url
  - key: GENERIC_TIMEZONE
    value: America/Santiago
